from functools import partial
import argparse

from flask import Flask
from flask import Response
from flask import g
from flask import json

from . import api
from . import api_docs
from . import db
from . import models
from . import utils


app = Flask(__name__)


@app.route('/docs')
def docs():
    return Response(api_docs.make_docs(api.api_routes),
                    mimetype='text/plain')


def routed_fn(path, route):
    with g.conn as conn:
        pass
    return ""


# add all of the autogenerated API endpoints
for path, route in api.api_routes.items():
    app.add_url_rule(path,
                     route.basename,
                     partial(routed_fn, path, route),
                     methods=[route.method])


@app.route('/')
def slash():
    return 'Hello, World!'


def server(conn, port, debug=True):

    # the sqlite connection isn't thread-safe, so we have to wrap it in a mutex
    app.config['conn'] = utils.LockBox(conn)

    app.run(port=port, debug=debug)

